### PR TITLE
Created draft SIA service HowTo notebook

### PR DESCRIPTION
**Pull request by knutago**
Have written a SIA Service HowTo that exposes (almost) all of the possible SIA service endpoints, shows a basic example of using the service to create an image cutout, and adapts Robert's function to download the deepest image to demonstrate how to automate the search for a particular kind of cutout.

### CODE REVIEW

**Comment by mjfitzpatrick** [comment]
Also, the bandpass names aren't always a simple 'g', 'r', 'i' etc and will vary depending on instrument or pipeline.  A general search of the NSA will turn up the full DECam filter name, unless that is passed in explicitly the equality match in download_deepest_image() won't find anything.

**Comment by knutago** [comment]
Thanks for the review, will work on these comments.  I meant to use the startswith() function in NumPy in the download_deepest function, as done in the example earlier in the notebook.

**Comment by knutago** [comment]
So on saving the cutout to VOSpace, I had the hope that for a URL of:
url='http://datalab.noao.edu/svc/cutout?col=&siaRef=c4d_130905_015144_osi_g_v1.fits.fz&extn=5&POS=335.0,0.0&SIZE=0.1,0.1'

that sc.load('test_image.fits',url) would do it.  In my regular user account (so one without the current VOSpace problem), it yields 'OK' and an empty file test_image.fits.

**Comment by knutago** [comment]
Have addressed @mjfitzpatrick review comments, only waiting on resolution of the sc.load() issue.

**Comment by knutago** [comment]
sc.load() issue resolved, knut_sia branch updated.

**Pull request merged**
