### PR TITLE
Updates for Dwarf Gals in DES DR1

### PR DESCRIPTION
**Pull request by jacquesalice**

### CODE REVIEW

**Comment by rnikutta** [comment]
@jacquesalice The NB in this branch sets these service URLs:

```
qc.set_svc_url('http://dltest.datalab.noao.edu/query')
sc.set_svc_url('http://dltest.datalab.noao.edu/storage')
```

This is not production, right? Let me know when you have fixed it.

Also, it would make more sense to have PRs per-notebook (i.e. not multiple NBs in one PR).

**Comment by jacquesalice** [comment]
@rnikutta No it's not production... The Datalab Command Line Client notebook added itself to this PR again!! I did not mean for more than one notebook to be on this PR. I'll delete it.

**Comment by rnikutta** [comment]
@jacquesalice Can you please do one more re-run (and save ipynb + html), to get rid of your username printed below the login/whoami cell? Otherwise the NB is good to merge. Thanks.

**Comment by jacquesalice** [comment]
@rnikutta Done!

**Comment by rnikutta** [comment]
..and the html please ;-)

**Comment by jacquesalice** [comment]
@rnikutta Both the ipynb and the html should be there! Are they not? [(https://github.com/noaodatalab/notebooks-latest/tree/jacquesalice-patch-dwarfdesdr1/03_ScienceExamples/DwarfGalaxies)]

**Comment by rnikutta** [comment]
Ah, my bad. I had local changes in my clone, and a git pull aborted which I didn't notice. Did a git stash, and git pull again, and now the html and ipynb show 'demo00'. Thanks! Merging.

**Pull request merged**
