### PR TITLE
Adding Colab-ready notebooks

### PR DESCRIPTION
**Pull request by DavidVargasMora**
Here are the eleven Teen Astronomy Café notebooks updated to work with Colab.

In order to keep the 'desktop' versions of the notebooks separate from the updated ones, the latter will be stored in the '**e-**TeenAstronomyCafe' folder.

PD: Although, we checked carefully, there could still be a few minor URL adjustments needed in the code.

### CODE REVIEW

**Comment by jmencisom** [comment]
Hi @rnikutta,

I wonder if there is any pending issue from our side or perhaps we can move forward with this pull request.

I really appreciate your support.

Please let us know.
--Javier

**Comment by rnikutta** [comment]
Hi @jmencisom , @DavidVargasMora,

there a big problem with accepting the PR:

all the simulation txt files under `04_Galactic_Neighborhood/Data/Sims/M33_VLowRes/` , that's *too much data* for version control, and would make each cloning too time and data-consuming. In the non-e version of TeenAstronomyCafe notebooks, we did not include the txt files in the repo, but the simulation notebook `06_EPO/TeenAstronomyCafe/04_Galactic_Neighborhood/Galactic_Neighborhood.ipynb`  instead pointed to a special data partition at Data Lab, where the files could be fetched from, like this:

```
COMD3 = CenterOfMass("/nbdata/Sims/M33_VLowRes/M33_%s.txt"%thissnap,particle_type)
```

Could you do something like this again in the e-TeenAstronomyCafe version?

**Comment by jmencisom** [comment]
Thank you @rnikutta, we are going to have a look at this, and return to you soon.

**Comment by DavidVargasMora** [comment]
Hi @rnikutta!

Sure, that could work. We would only need a link to the partition where the files would be hosted, then we would update the link in the notebooks, and erase the files from the repository.

Thanks a lot!

**Comment by rnikutta** [comment]
Hi @DavidVargasMora and @jmencisom 

perfect! The data partition is, as before (see my previous comment): ``/nbdata/Sims/M33_VLowRes/``

The notebooks loads the txt file in this line (in a loop over file names):

``COMD3 = CenterOfMass("/nbdata/Sims/M33_VLowRes/M33_%s.txt"%thissnap,particle_type)``

Now, this is to run the Data Lab notebook server. To run it on Colab I guess you'd have to provide the data dir somewhere else?

**Comment by DavidVargasMora** [comment]
Oh, unfortunately we need a direct link to the files, as Colab does not work with relative paths. Users would have to create the folders and upload the files to the session storage every time they run the notebook, so that's not an option.

It would be great if we could host the files somewhere in Data Lab's server so we could access them through a public URL like: 

https://datalab.noao.edu/nbdata/Sims/M33_VLowRes/M33_%s.txt

**Comment by rnikutta** [comment]
I'll check with the team immediately. To be in agreement: are we talking only about the files under ``/nbdata/Sims/M33_VLowRes/`` ? Or other aux files as well?

**Comment by DavidVargasMora** [comment]
Thanks a lot @rnikutta!
We would need all the files required to run NB04, so not only the files under `/nbdata/Sims/M33_VLowRes/`, but the entire 'nbdata' folder.

Somewhere during the project we received this [link ](https://drive.google.com/file/d/1d724_Y9d49DCeLl1MEs3EPpgFxOzrOSv/view) to download said folder, but it was 2GB so we had to do some cleaning and reduce file sizes in order to make it more manageable, the reduced files are on under `04_Galactic_Neighborhood/Data` in this commit. Do you want me to share a different links to those files so you and the team can download it?

**Comment by DavidVargasMora** [comment]
We would only need [these ](https://drive.google.com/file/d/16i2XUHSL288hu4qTwjsm_dmqsJqensYZ/view?usp=sharing)files to run NB04 perfectly.

**Comment by rnikutta** [comment]
@DavidVargasMora You've probably seen Mike's email. The data are now public at: https://datalab.noao.edu/nbdata/

**Comment by DavidVargasMora** [comment]
This is perfect @rnikutta, thanks a lot!
I will do the adjustments and make the pull request again.

**Pull request closed without merging**
