### PR TITLE
First commit of the finished notebook draft

### PR DESCRIPTION
**Pull request by rdzudzar**

### CODE REVIEW

**Comment by rdzudzar** [comment]
This is an interactive exploration of the HI (neutral hydrogen, radio data) and optical data.

**Comment by rdzudzar** [comment]
Hi, I'm sorry this is my first pull request; I'm doing it again because the files were not uploaded correctly

**Comment by rnikutta** [comment]
Hi Robert,

thanks so much for offering a contributed notebook to Data Lab. We are thrilled!

We have some suggestions about how to make your notebook even more useful to other Data Lab users, and I will write to you about it here, likely Thursday or Friday... Apologies that I can't do it sooner, but I'm stuck with an important deadline here.

Talk to you in a day or two, thanks!
Robert

**Comment by rdzudzar** [comment]
Hi,
That is great! No worries about time, weekends are usually when I get most
things done, either way.

Best regards.
Robert

чет, 6. јун 2019. у 13:25 Robert Nikutta <notifications@github.com> је
написао/ла:

**Comment by rnikutta** [comment]
Hi Robert,

without further ado, here some larger and smaller suggestions of how
to further improve the already impressive notebook:

Proposing general / large changes:
==================================

1) For demo purposes, reduce the number of processed sources (to
  speed up execution). 10 should be plenty.

2) Use VOSpace to save products (images, data files, etc)

E.g.:

```
  sc.mkdir('vos://outputdir')  # make a dir in user VOSpace (do this only once of course)
  plt.plot(...) # create a plot
  plt.savefig('fooplot1.pdf')  # save figure in local CWD
  sc.put(fr='fooplot1.pdf',to='vos://outputdir/fooplot1.pdf')  # copy PDF from local to vospace
  rm fooplot1.pdf  # delete local
```

If you wish that the files be visible to other DL users, put them
somewhere inside the vos://public/ directory, e.g.

```
  sc.mkdir('vos://public/outputdir')  # make a dir in user VOSpace (do this only once of course)
  # ...
  sc.put(fr='fooplot1.pdf',to='vos://public/outputdir/fooplot1.pdf')  # copy PDF from local to vospace
 ```

3) Use a DL cutout service to get thumbnails, rather than downloading remote images.

Have a look at this notebook, which demonstrates how to get image
cutouts at a given position using one of the many SIA (Simple
Image Access) services offered by DL:

In your Jupyter notebook space:

notebooks-latest/04_HowTos/SiaService/How_to_use_the_Simple_Image_Access_service.ipynb

or on Github:

https://github.com/noaodatalab/notebooks-latest/tree/master/04_HowTos/SiaService


Other specific suggestions:
===========================

1) Imports
Please only import what you will use. E.g. no need to import helpers
from dl if you're not using it. Same with queryClient. (Please also
check all of your custom imports whether they are needed or not). Also
check for unnecessary double imports, in the sense that if you're already doing

```
  from astropy import coordinates
```

you don't need to do

```
  from astropy.coordinates import SKyView
```

etc.

2) Authentication

To use vospace, user must be authenticated. Please use the standard line

```
  token = ac.login(input("Enter user name: "),getpass("Enter password: "))
```

Specifically, no raw_input, and no Py2 syntax (we're deprecating it).

3) Printing diagnostics, e.g. of Pandas dataframes:

A ``df.head()`` is probably sufficient (i.e. don't do just ``df``), and prints only a few rows of a
potentially long table.

4) Is the custom HTML code around Bokeh really necessary? Try to keep
   the notebook "clean" and useful to users who want to learn about /
   experimental with HIPASS and spectral data. (not saying you can't
   use this technique, just suggesting to simplify the notebook a
   bit).

5) Delete cells that are not used (i.e. commented out), or empty (as
   e.g. at the very bottom of the notebook).

Looking forward to your update. Keep adding to the PR, thanks!

**Comment by rdzudzar** [comment]
Hi Robert, 
Thank you for your detailed comments and suggestions.
I added notebook with some changes as suggested, however, with some suggested changes I have trouble (noted below), and some I think are not possible at the moment to make. 
I will summarize.

### Changes which I made are:
1.  Cleaned the import - I removed ones not used. Suggested removal of the SkyView resulted in notebook not working, so it is required to have both SkyCoord and SkyView. 
2.  I removed empty cells and code which was commented.
3. I added additional comments/descriptions at some places. 
4. I left authentications so that users can place their name/password as suggested.
5. I placed df.head() when printing the pandas dataframe. 
6. Sources by default are now 10 and it takes less than a minute to run the entire notebook.

### Changes which gives me troubles:
**1. vospace:**

I can make directories and store necessary paths with:
`sc.mkdir('vos://HIPASS_spectra_'+(selected)+'/')  # make a dir in user VOSpace `
`sc.mkdir('vos://HIPASS_images_'+(selected)+'/')  # make a dir in user VOSpace `
`spectra_path ='vos://HIPASS_spectra_'+(selected)+'/'`
`images_path = 'vos://HIPASS_images_'+(selected)+'/'``

Later I managed to save images/spectra as:
`fig.savefig('{0}'.format(idx), overwrite=True)`
`sc.put(fr='*.png', to=spectra_path+'{0}'.format(idx)+'.png')`
`plt.close(fig)`

And I managed to move images into vospace with:
`sc.put(fr='*.png', to=images_path)  # copy PDF from local to vospace`

Hovewer, I did not manage to remove all created images from the current directory all at once, I can do one by one, but I'm guessing user should not do that. Saving images based on their idx is important because bokeh will not be able to link them properly. Thant brings me to the issue with vospace which I couldn't solve:
In notebook cell "Extracting/Sorting images and spectra which we have" -- downloaded images/spectra need to be accessed and sorted as integers: 0.png, 1.png, 2png. etc. because otherwise image order will be 0.png, 1.png, 10.png. 2.png etc. and they will be linked wrong in bokeh. Using vospace, I did not manage to performe this sorting. I can get list of images with sc,ls however it is not the same as listdir and I always get empty list. I don't know how to performe this sorting in vospace. 

**2. Image cut-out:**

Does DataLab have access to DSS images? 
In the provided notebook, and while I searched through the datalab website, I could not find are there available and how to access DSS survey. HIPASS survey is on the Southern Sky and if DES is used (which I agree is much better and deeper and can be in colour) many galaxies will be left-out blank because it does not cover whole sky. My plan was for the future extension to this notebook or creating similar one,  with DES color images and other multiwavelength data (GALEX etc.). Since this would be substancial change it requires a bit more time and new notebook. 

**3. bokeh html code**

Images require to have .html code, otherwise they will not be displayed, I added more comments in that cell, and said explicitly that what is matter is to see where linking is made '@item_name' because this is how user can call items from source.

I hope that I did not miss any of the given suggestions. If you can provide me with help how to deal with the vospace sorting images, I'm happy to enter those changes to the notebook. 

Cheers,
Robert

**Comment by rnikutta** [comment]
Hi Robert,

thank for your additional work! A few last comments/suggestions:

> 1. vospace (sorting, removing local copies)

You could save your images with a double-digit format, i.e.
```
images_path = 'vos://HIPASS_images_' + (selected)
# ... looping over idx
fname = 'hipass_{0:02d}.png'.format(idx)
fig.savefig(fname, overwrite=True)
sc.put(fr=fname, to=images_path+os.path.sep+fname)
```
i.e. the names will be `hipass_00.png`, `hipass_01.png`, `hipass_02.png`, ...
This should sort correctly.

For the removal of the local copies, this should work:
```
!rm -f hipass_*png
```
Having a prefix like "hipass" also protects from inadvertantly
deleting unrelated files in the user directory (for instance
other PNG files).

> 2. Image cut-out:
> 
> Does DataLab have access to DSS images?

Not yet.

There are some other surveys that cover the South, e.g. SPLUS, or
SMASH (partially), and you can also look into the

`DEF_ACCESS_URL = "http://datalab.noao.edu/sia/coadd_all"`

SIA service. But if you don't find what you need, no worries. The
notebook can be alway updated later, if new image sets become
available.

> 3. bokeh html code
> 
> Images require to have .html code, otherwise they will not be
> displayed, I added more comments in that cell, and said
> explicitly that what is matter is to see where linking is made
> '@item_name' because this is how user can call items from source.

Understood!

Please make one more push, then I'll merge.

Thanks again!
Robert

**Comment by rdzudzar** [comment]
Hi Robert,

I entered changes and made new commit.
 In this version, images/spectra are saved to VOSpace and removed from the local directory; thus user authentication is used. 
Additional `if` conditions are made, to make sure that user specified only one dataset from (most_massive, least_massive, confused), here was a bug which allowed multiple selection at once, but carried out only one. 
Thank you for the suggestion for file_name saving, I was not aware that this was possible, now it's much better and the additional part for integer sorting is no longer necessary, thus I removed it. I added two additional zeros `{0:04d}`, in case used decides to try with over 1000 galaxies. 
For cut-out image service, I agree that such functions are included at some point in the future when there is a bit better sky coverage. 

Best regards,
Robert

**Comment by rnikutta** [comment]
Hi Robert, mnay thanks for your updates.

Final requests:

- Please remove (as requested) this:
```
# Python 2/3 compatibility
try:
    input = raw_input
except NameError:
    pass
```
- If I understand the logic correctly, you want to allow only one of the following to be `True` at any given time: `most_massive` or `least_massive` or `confused`, correct? A much simpler way would be then to have the user directly state that. E.g.
```
# assign only one of the following: 'most_massive', 'least_massive', 'confused'
selected = 'most_massive'

# and then further down (using a dictionary)
d = {
  'most_massive' : (False, 'logHI_mass_approx'),
  'least_massive' : (True, 'logHI_mass_approx'),
  'confused' : (False, 'cf')
}

ascending = d[selected][0]
by_ = d[selected][1]
```
This should simplify the logic & selection significantly, to the benefit of the user, and the notebook (cleaner).

Many thanks for your patience. We're almost there!

**Comment by rdzudzar** [comment]
Hi Robert,
The final requests are added to the notebook, with the simplified check, and raising an error if the selection is wrong.
Cheers,
Robert

**Comment by rnikutta** [comment]
Robert, apologies for the delay. I wanted to merge your notebook now, but one cell won't run, the "Extracting images and spectra" under "Setting up Bokeh for interactive examination":

```
# Path to the storred images. 
my_im_path = '../vospace/HIPASS_images_'+str(interactive)+'/'
my_sp_path = '../vospace/HIPASS_spectra_'+str(interactive)+'/'

# List the files in the path where images/spectra are storred and append the VOSpace path to it (my_sp_path and my_im_path)
# All paths to files will be storred into list_spectra and list_images which will be used in bokeh.
list_spectra = []
list_images = []
for each_file in listdir(my_im_path):
    New_list_s = my_sp_path+str(each_file)
    New_list_i = my_im_path+str(each_file)
    list_spectra.append(New_list_s)
    list_images.append(New_list_i)
```
Gives:
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-18-aa32dcac6ae6> in <module>()
      7 list_spectra = []
      8 list_images = []
----> 9 for each_file in listdir(my_im_path):
     10     New_list_s = my_sp_path+str(each_file)
     11     New_list_i = my_im_path+str(each_file)

FileNotFoundError: [Errno 2] No such file or directory: '../vospace/HIPASS_images_most_massive/'
```
The reason is that you assume a specific location for `my_im_path`. Better to resolve first the user's homedir, then add the vospace part of the path, i.e.:

```
my_im_path = os.path.expanduser('~') + os.path.sep + 'vospace/HIPASS_images_' + str(interactive)
```
Note that the final `+'/'` is not neeed. Note also that it's better to use `os.path.sep` rather than `'/'` as the latter is not OS-independent.

Please also change in the same fashion how `my_sp_path` is defined. Push again after that, thanks!

**Comment by rdzudzar** [comment]
Hi,
I see, yes, I was running from a different folder, which was just above the vospace. 
I placed as suggested `my_im_path ` and `my_sp_path`, when I print them out it gives me this path: `/home/jail/./dlusers/rdzudzar/vospace/HIPASS_images_most_massive/`. However, with this path, bokeh is not finding images to display (using list `'/home/jail/./dlusers/rdzudzar/vospace/HIPASS_spectra_most_massive/hipass_0000.png'`  etc.). Now, either I'm missing something in the given path or bokeh has some compatibility issues with vospace? 

Also, when I manually check into vospace for created images, when using provided path they are not updated e.i. images from the program are either not saved or saved somewhere else? In previous iterations, when images were moved to vospace, there would be print message `(1 / 1) hipass_0000.png -> vos://HIPASS_images_most_massive/hipass_0000.png` etc. for inages. I also tried using ` vos://HIPASS_images_most_massive/` for list of images, but as well with this, bokeh did not recognized the path and didn't display image on hover. 

Any idea if this is some bigger issue, or just an error in path?
Thank you.

**Comment by rnikutta** [comment]
Hi Robert, I confirm: it does not like absolute paths for some reason. And to construct a relative path to vospace, you must know where you are... This should do the trick (I tested it from two different levels of directory depth):
```
# where you do imports
from os.path import relpath, expanduser, sep

# where you construct your paths to vospace subdirs
vopath = relpath(expanduser('~')) + sep + 'vospace' + sep
my_im_path = vopath + 'HIPASS_images_' + str(interactive) + sep
my_sp_path = vopath + 'HIPASS_spectra_' + str(interactive) + sep
```
This will always generate the correct relative path to vospace.

Can you please make this final change and push again? Thanks!

**Comment by rdzudzar** [comment]
Hi, 
I added relative path and it seems to be working now.
Thank you,
Robert

**Comment by rnikutta** [comment]
Thanks, merging!

If you wanted, you could also replace (two instances of it in the notebook) this:
```
gal_name = str(df['HIPASS'][galaxy_name]).strip('b\' ')
```
with the cleaner:
```
gal_name = df['HIPASS'][galaxy_name]).strip().decode()
```

**Pull request merged**
