### PR TITLE
Updates for How To Use SDSS Data

### PR DESCRIPTION
**Pull request by jacquesalice**

### CODE REVIEW

**Comment by weaverba137** [comment]
This PR adds the Command Line Client notebook, but so does #59 & #61.

Also, separately I'm updating the SDSS Data notebook to DR16.  I could coordinate if you want.  I just want to avoid git merge conflicts, which are not my favourite things.

**Comment by rnikutta** [comment]
Please do coordinate @weaverba137 , much appreciated!

**Comment by jacquesalice** [comment]
Yes I could not figure out how to remove the Command Line Client notebook from the PRs 59,60,61.... I only wanted to add the Command Line Client notebook to my branch, not submit a PR for it since it is not yet complete... but then it added itself to those 3 PR 'patches'. Maybe if I just delete the Command Line Client file from my branch and upload it somewhere else?

**Comment by jacquesalice** [comment]
As to your second point @weaverba137 that's fine by me! How can I be of help in your coordination? Should I close this PR?

**Comment by weaverba137** [comment]
Looking closer, #59, #60 & #61 all have the same three commits involving the command line client, then a fourth separate commit involving the notebook in question.

So if you can remove those commits from the history the other PRs would still work, but it's fine to close this one.

**Pull request closed without merging**
