### PR TITLE
Improved ANTARES DevKit

### PR DESCRIPTION
**Pull request by gnarayan**
- new filter examples
- more documentation
- uses the latest version of DevKit API

### CODE REVIEW

**Comment by gnarayan** [comment]
cc @cstubens @rnikutta

**Comment by cstubens** [comment]
Thanks a bunch @gnarayan 👌

**Comment by rnikutta** [comment]
@gnarayan Is it correct that you've also (heavily) updated a Teen Cafe notebook together with this? Thanks.

**Comment by gnarayan** [comment]
Removed the teen astro cafe notebook - nothing was changed there, but the version had compiled output included. This might actually be a good idea for the EPO notebooks, since it's helpful to see the output with nbviewer without having to download and run, but that's for Connie and crew to decide.

**Pull request merged**
