### PR TITLE
Dwarfs delve

### PR DESCRIPTION
**Pull request by jonahmedoff**
Hi @knutago, this is an update to DwarfGalaxiesIn... notebook for DELVE DR1. Comments and review welcome.

### CODE REVIEW

**Comment by kadrlica** [comment]
Thanks @jonahmedoff, looks great!

**Comment by knutago** [comment]
Hi Jonah,

Notebooks looks good!  Just a few minor nits:
1.  Can your name and email in the __author__ list in the first cell?  I don't think you need the other author names in there, as you already acknowledge them in the next cell.
2. In the Data Lab disclaimer line, can you please edit the URL to be https://datalab.noirlab.edu/disclaimers.php ?
3. Under the cell Submit the query, I'd recommend saving straight to your Pandas dataframe, e.g.:
 %time
 R = qc.query(sql=query,fmt='pandas')
 then you don't need the extra convert step.  
 Likewise in the cell under Query the database for stars near the peak.

**Comment by jonahmedoff** [comment]
I just made these changes and I committed and pushed them onto github. Let
me know if there were any issues or if there's anything else I need to do.

Thank you,

Jonah Medoff

**Comment by knutago** [comment]
Hi Jonah,

Sorry for the delay in looking at this again!  Two last minor issues:

1.  Didn't catch this before, but the SIA service URL in the image cutout section should be https://datalab.noirlab.edu/sia/nsa, as the noao.edu domain will disappear soon.  Can you change it in the code cell and in the comment above it?
2. Thanks for making the change to store directly as a Pandas dataframe.  Can you remove the text indicating that you use the helper function to convert to Pandas?

That's all!

**Pull request merged**
