### PR TITLE
Update SDSS notebook to DR16

### PR DESCRIPTION
**Pull request by weaverba137**
This PR updates the SDSS data notebook to DR16.  @jacquesalice , please take a look and add any changes to this branch.

### CODE REVIEW

**Review by jacquesalice — CHANGES_REQUESTED** [review]
1. Add the following to keywords: 'plot:color-color','plot:histogram','galaxies'.

2. The Table of Contents links did not bring me anywhere...

3. Remove the following imports (since they are not used in the notebook):
    `from contextlib import contextmanager`
    `from time import sleep`

4. Include import of `authClient as ac`  

5. Include Authentication section that says the following in Markdown followed by a cell with code:
Authentication
Much of the functionality of Data Lab can be accessed without explicitly logging in (the service then uses an anonymous login). But some capacities, for instance saving the results of your queries to your virtual storage space, require a login (i.e. you will need a registered user account).
If you need to log in to Data Lab, issue this command, and respond according to the instructions:
```
#ac.login(input("Enter user name: (+ENTER) "),getpass("Enter password: (+ENTER) "))
ac.whoAmI()
```

**Comment by jacquesalice** [comment]
Not necessary but makes the code a little cleaner-looking (at least to me):
```
cmmr = result['cmodelmag_r']
cmmi = result['cmodelmag_i']
cpar = auxcolor['c_par']
cperp = auxcolor['c_perp']
dperp = auxcolor['d_perp']
pmr = result['psfmag_r']
pmi = result['psfmag_i']
pmz = result['psfmag_z']
mmg = result['modelmag_g']
mmr = result['modelmag_r']
mmi = result['modelmag_i']
mmz = result['modelmag_z']
f2mi = result['fiber2mag_i']

LOWZ = ((cmmr < (13.5 + cpar/0.3)) & 
        (np.abs(cperp) < 0.2) &
        (cmmr > 16.0) & (cmmr < 19.6) &
        ((pmr - cmmr) > 0.3))

CMASS = ((cmmi < (19.86 + 1.6*(dperp - 0.8))) &
         (cmmi > 17.5) & (cmmi < 19.9) &
         (dperp > 0.55) &
         ((pmi - mmi) > (0.2 + 0.2*(20.0 - mmi))) &
         ((pmz - mmz) > (9.125 - 0.46*mmz)) &
         ((mmr - mmi) < 2) &
         (f2mi < 21.5) & 
         (rdev_i < 20))
```

And then: 

```
fig = plt.figure(dpi=100)
ax = fig.add_subplot(111)
p1 = ax.plot(mmg - mmr,
             mmr,
             label='model', linestyle='none',
             marker=',', markeredgecolor='k', markerfacecolor='k')
p2 = ax.plot(mmg[LOWZ] - mmr[LOWZ],
             mmr[LOWZ],
             label='LOWZ', linestyle='none',
             marker='s', markeredgecolor='g', markerfacecolor='none')
p3 = ax.plot(mmg[CMASS] - mmr[CMASS],
             mmr[CMASS],
             label='CMASS', linestyle='none',
             marker='o', markeredgecolor='r', markerfacecolor='none')
foo = ax.set_xlim([-2, 6])  # Adjust x axis here. 
foo = ax.set_ylim([24, 15])  # Adjust y axis here.
foo = ax.set_xlabel('g - r')
foo = ax.set_ylabel('r')
foo = ax.set_title('Color-Magnitude of SDSS (DR{0:d}) Galaxies'.format(release))
l = ax.legend(numpoints=1)
```

And also: 

```
fig = plt.figure(dpi=100)
ax = fig.add_subplot(111)
p1 = ax.plot(mmg - mmr,
             mmr - mmi,
             label='model', linestyle='none',
             marker=',', markeredgecolor='k', markerfacecolor='k')
p2 = ax.plot(mmg[LOWZ] - mmr[LOWZ], 
             mmr[LOWZ] - mmi[LOWZ],
             label='LOWZ', linestyle='none',
             marker='s', markeredgecolor='g', markerfacecolor='none')
p3 = ax.plot(mmg[CMASS] - mmr[CMASS], 
             mmr[CMASS] - mmi[CMASS],
             label='CMASS', linestyle='none',
             marker='o', markeredgecolor='r', markerfacecolor='none')
foo = ax.set_xlim([-1, 4])  # Adjust x axis here. 
foo = ax.set_ylim([-1, 4])  # Adjust y axis here. 
foo = ax.set_xlabel('g - r')
foo = ax.set_ylabel('r - i')
foo = ax.set_title('Colors of SDSS (DR{:d}) Galaxies'.format(release))
l = ax.legend(numpoints=1)
```

**Comment by jacquesalice** [comment]
Under Plotting SDSS Spectra title, in the cell that defines the `plot_spectrum` function, change `foo = ax.set_title("{0:04d}-{1:05d}-{2:04d}".format(plate, mjd, fiber))` ----> `foo = ax.set_title("plate-mjd-fiber: {0:04d}-{1:05d}-{2:04d}".format(plate, mjd, fiber))`

**Comment by jacquesalice** [comment]
Under Display SDSS Images title, in the cell that defines the `extract_frame` function, should 
`sas='sdss_dr14://'` be 
`sas='sdss_dr16://'` ?
If so, then you will also need to change: 
`fm = '{0}eboss/photoObj/frames/301/{1:d}/{2:d}/frame-{3}-{1:06d}-{2:d}-{4:04d}.fits.bz2'.format(sas, run, camcol, band, field)`
If you did mean to have dr14, under the section title we should say something along the lines of "Note that the following example uses dr14 to extract frame".

**Comment by jacquesalice** [comment]
Also under Display SDSS Images, in the `display_frame` function, change:
`cb = plt.colorbar()` ----> `cb = plt.colorbar(shrink=0.6)`
That way the colorbar is the same size as the plot.

**Comment by weaverba137** [comment]
>     1. Add the following to keywords: 'plot:color-color','plot:histogram',plot:cmd,'galaxies'.

Done.

>     2. The Table of Contents links did not bring me anywhere...

The links work for me, so I have to ask how you tested this.

>     3. Remove the following imports (since they are not used in the notebook):
>        `from contextlib import contextmanager`
>        `from time import sleep`

Done.

>     4. Include import of `authClient as ac`

Done.

>     5. Include Authentication section that says the following in Markdown followed by a cell with code:
>        Authentication
>        Much of the functionality of Data Lab can be accessed without explicitly logging in (the service then uses an anonymous login). But some capacities, for instance saving the results of your queries to your virtual storage space, require a login (i.e. you will need a registered user account).
>        If you need to log in to Data Lab, issue this command, and respond according to the instructions:
> 
> 
> ```
> #ac.login(input("Enter user name: (+ENTER) "),getpass("Enter password: (+ENTER) "))
> ac.whoAmI()
> ```

Done.

**Comment by weaverba137** [comment]
> Under Plotting SDSS Spectra title, in the cell that defines the `plot_spectrum` function, change `foo = ax.set_title("{0:04d}-{1:05d}-{2:04d}".format(plate, mjd, fiber))` ----> `foo = ax.set_title("plate-mjd-fiber: {0:04d}-{1:05d}-{2:04d}".format(plate, mjd, fiber))`

Done.

**Comment by weaverba137** [comment]
> Under Display SDSS Images title, in the cell that defines the `extract_frame` function, should
> `sas='sdss_dr14://'` be
> `sas='sdss_dr16://'` ?
> If so, then you will also need to change:
> `fm = '{0}eboss/photoObj/frames/301/{1:d}/{2:d}/frame-{3}-{1:06d}-{2:d}-{4:04d}.fits.bz2'.format(sas, run, camcol, band, field)`
> If you did mean to have dr14, under the section title we should say something along the lines of "Note that the following example uses dr14 to extract frame".

Done.  The change dr14 -> dr16 is all that is necessary.  Under the hood they all point back to the same data anyway.

**Comment by weaverba137** [comment]
> Also under Display SDSS Images, in the `display_frame` function, change:
> `cb = plt.colorbar()` ----> `cb = plt.colorbar(shrink=0.6)`
> That way the colorbar is the same size as the plot.

Done.

**Comment by weaverba137** [comment]
> `ac.whoAmI()`

There is a minor issue with this: if the author of the notebook actually runs the cell, with that uncommented, the author's username will be printed in the notebook.

**Comment by weaverba137** [comment]
> Not necessary but makes the code a little cleaner-looking (at least to me):

I'm going to skip this one.  I think this actually makes the code more complicated and potentially error-prone.

**Comment by weaverba137** [comment]
Updates checked in.  I think the only thing that needs to be resolved is the table of contents links.

**Comment by jacquesalice** [comment]
> > `ac.whoAmI()`
> 
> There is a minor issue with this: if the author of the notebook actually runs the cell, with that uncommented, the author's username will be printed in the notebook.

Ah okay should we leave that part # commented as well?

**Comment by jacquesalice** [comment]
> Updates checked in. I think the only thing that needs to be resolved is the table of contents links.

To view the file I went [here](https://github.com/noaodatalab/notebooks-latest/blob/d5b3d286b61a34b0d41be50f86de95611e0ae250/04_HowTos/FileService/How_to_use_SDSS_Data.ipynb). It may just be in this way that the table of contents links aren't clickable.

**Comment by weaverba137** [comment]
@jacquesalice, I think all the changes were made some time ago, could you re-review?

**Comment by jacquesalice** [comment]
> @jacquesalice, I think all the changes were made some time ago, could you re-review?

Sure thing.

**Comment by jacquesalice** [comment]
1. Under 'BOSS Galaxies in the SDSS Photometric Catalog', the second paragraph needs a closing parenthesis "(see the resolve documentation for further details".

2. Also under 'BOSS Galaxies in the SDSS Photometric Catalog', in the cell under 'Compute the cuts' remove the #'s 

Otherwise it looks good!

**Review by jacquesalice — APPROVED** [review]

**Comment by weaverba137** [comment]
Changes are in, merge when ready.

**Comment by rnikutta** [comment]
Let me take this NB for a spin quick...

**Comment by rnikutta** [comment]
Are proper indices computed on sdss_dr16? This query for instance expires after 300s:

```
%%time
q = "SELECT COUNT(*) AS nrows FROM {0}.specobj".format(schema)
result = qc.query(adql=q, fmt='csv')
print(result)
```
and another previous query also runs quite long with 2m40s:

```
print(q)
SELECT rerun, run, camcol, field, objid, ra, dec, devrad_i, 
modelmag_u, modelmag_g, modelmag_r, modelmag_i, modelmag_z, 
cmodelmag_u, cmodelmag_g, cmodelmag_r, cmodelmag_i, cmodelmag_z, 
psfmag_u, psfmag_g, psfmag_r, psfmag_i, psfmag_z, 
fiber2mag_u, fiber2mag_g, fiber2mag_r, fiber2mag_i, fiber2mag_z
FROM sdss_dr16.photoplate WHERE (resolvestatus & 256) != 0 LIMIT 100000

%%time
try:
    vot = qc.query(sql=q, fmt='votable', async_=False, timeout=300)
except Exception as e:
    print(e.message)
else:
    result = parse_single_table(BytesIO(vot.encode('utf-8'))).array
    rdev_i = result['devrad_i']/0.396  # convert back to pixels
    auxcolor = auxilliary_colors(result)
```

**Comment by weaverba137** [comment]
I've run through this notebook multiple times in recent days.  I have never seen that problem before.

**Comment by weaverba137** [comment]
O, hey, the TAP service is down!

**Comment by rnikutta** [comment]
I guess we're crashing.. Zabbix alerts plus Tomcat restart... I'll try again after it's back up.

**Comment by rnikutta** [comment]
Ok, count(*) query is now 5s, good.

First invocation of `plot_spectrum(4424, 55532, 952, showsky=True)` fails though with

```
---------------------------------------------------------------------------
MissingSchema                             Traceback (most recent call last)
<ipython-input-23-123688b4e803> in <module>
----> 1 plot_spectrum(4424, 55532, 952, showsky=True)

<ipython-input-22-dd3e846257dc> in plot_spectrum(plate, mjd, fiber, showsky, **kwargs)
     47         If ``True``, plot the sky spectrum
     48     """
---> 49     wavelength, flux, ivar, sky = extract_spectrum(plate, mjd, fiber, **kwargs)
     50     fig = plt.figure(dpi=100)
     51     ax = fig.add_subplot(111)

<ipython-input-22-dd3e846257dc> in extract_spectrum(plate, mjd, fiber, run2d, release, sas)
     23     """
     24     vopath = "{0}sdss/spectro/redux/{1}/{2:04d}/spPlate-{2:04d}-{3:05d}.fits".format(sas, run2d, plate, mjd)
---> 25     with fits.open(sc.get(vopath, mode='fileobj')) as hdulist:
     26         hdr = hdulist[0].header
     27         flux = hdulist[0].data[fiber-1, :]

/data0/sw/anaconda3/lib/python3.7/site-packages/noaodatalab-2.18.10-py3.7.egg/dl/Util.py in __call__(self, *args, **kw)
     80             return function(self.obj, *args, **kw)
     81         else:
---> 82             return function(*args, **kw)
     83 
     84     def __repr__(self):

/data0/sw/anaconda3/lib/python3.7/site-packages/noaodatalab-2.18.10-py3.7.egg/dl/storeClient.py in get(optval, fr, to, token, mode, verbose, debug, timeout)
    410         return sc_client._get(fr=optval, to=to, token=def_token(token),
    411                             mode=mode, verbose=verbose, debug=debug,
--> 412                             timeout=timeout)
    413 
    414 @multimethod('sc',0,False)

/data0/sw/anaconda3/lib/python3.7/site-packages/noaodatalab-2.18.10-py3.7.egg/dl/storeClient.py in _get(self, token, fr, to, mode, verbose, debug, timeout)
   1600             url = requests.get(self.svc_url + "/get?name=%s" % nm,
   1601                                headers=hdrs)
-> 1602             r = requests.get(url.text, stream=False, headers=hdrs)
   1603             if mode == 'text':
   1604                 return scToString(r.content)

/data0/sw/anaconda3/lib/python3.7/site-packages/requests/api.py in get(url, params, **kwargs)
     73 
     74     kwargs.setdefault('allow_redirects', True)
---> 75     return request('get', url, params=params, **kwargs)
     76 
     77 

/data0/sw/anaconda3/lib/python3.7/site-packages/requests/api.py in request(method, url, **kwargs)
     58     # cases, and look like a memory leak in others.
     59     with sessions.Session() as session:
---> 60         return session.request(method=method, url=url, **kwargs)
     61 
     62 

/data0/sw/anaconda3/lib/python3.7/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    517             hooks=hooks,
    518         )
--> 519         prep = self.prepare_request(req)
    520 
    521         proxies = proxies or {}

/data0/sw/anaconda3/lib/python3.7/site-packages/requests/sessions.py in prepare_request(self, request)
    460             auth=merge_setting(auth, self.auth),
    461             cookies=merged_cookies,
--> 462             hooks=merge_hooks(request.hooks, self.hooks),
    463         )
    464         return p

/data0/sw/anaconda3/lib/python3.7/site-packages/requests/models.py in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
    311 
    312         self.prepare_method(method)
--> 313         self.prepare_url(url, params)
    314         self.prepare_headers(headers)
    315         self.prepare_cookies(cookies)

/data0/sw/anaconda3/lib/python3.7/site-packages/requests/models.py in prepare_url(self, url, params)
    385             error = error.format(to_native_string(url, 'utf8'))
    386 
--> 387             raise MissingSchema(error)
    388 
    389         if not host:

MissingSchema: Invalid URL 'The requested target URI is invalid': No schema supplied. Perhaps you meant http://The requested target URI is invalid?
```

**Comment by weaverba137** [comment]
Are you quite certain that the file service has been restored?

**Comment by rnikutta** [comment]
Zabbix reports OK status. I've now twice restarted the kernel and tried to re-run the NB. It fails at the first plot_spectrum(). Ben, could you try to reproduce this failure but running the NB again?

**Comment by weaverba137** [comment]
The VOSpace problem has been fixed, please try again.

**Comment by rnikutta** [comment]
Works very well, thank you. Merging.

**Pull request merged**
