### PR TITLE
Add ANTARES Filter DevKit

### PR DESCRIPTION
**Pull request by cstubens**

### CODE REVIEW

**Comment by rnikutta** [comment]
Thanks Carl. Minor revisions please:

- Please use PascalCase, both for directory names and file names (i.e. not "Pascal Case", i.e. no spaces)
- Don't go all-caps with Antares (i.e. not ANTARES)
- Drop the _yyyymmdd suffix, according to the latest template (in the same repo)

**Comment by rnikutta** [comment]
Final request for now: please add your new keywords ('ANTARES', 'transient') to ./keywords.txt

**Comment by rnikutta** [comment]
Obviously it wasn't obvious enough that keywords.txt is alphabetically sorted ;-) Can you please fix?

**Comment by cstubens** [comment]
> Obviously it wasn't obvious enough that keywords.txt is alphabetically sorted ;-) Can you please fix?

Ha! Sorry about that. Here you go.

**Pull request merged**
